In [20]:
#1. Write a Python Program to Add Two Matrices?
import numpy as np

mat_one = np.random.randint(10,size=(3,3))
mat_two = np.random.randint(10,size=(3,3))
result = mat_one+mat_two
print(f"A = \n{mat_one}\n \n B = \n{mat_two}\n \n A+B=\n{result}\n ")

A = 
[[1 4 9]
 [1 2 7]
 [0 5 9]]
 
 B = 
[[6 3 5]
 [1 9 3]
 [4 0 1]]
 
 A+B=
[[ 7  7 14]
 [ 2 11 10]
 [ 4  5 10]]
 


In [30]:
#2. Write a Python Program to Multiply Two Matrices?
import numpy as np

mat_one = np.random.randint(10,size=(3,3))
mat_two = np.random.randint(10,size=(3,3))
result = np.matmul(mat_one,mat_two)
print(f"A = \n{mat_one}\n \n B = \n{mat_two}\n \n A*B=\n{result}\n ")

A = 
[[8 3 0]
 [4 6 3]
 [0 3 6]]
 
 B = 
[[8 5 7]
 [8 2 9]
 [7 7 0]]
 
 A*B=
[[ 88  46  83]
 [101  53  82]
 [ 66  48  27]]
 


In [23]:
#3. Write a Python Program to Transpose a Matrix?
import numpy as np

mat = np.random.randint(10,size=(3,3))
mat_t = mat.T
print("before transpoe")
print(mat)
print("After transpse")
print(mat_t)


before transpoe
[[1 3 6]
 [6 8 2]
 [6 1 9]]
After transpse
[[1 6 6]
 [3 8 1]
 [6 2 9]]


In [27]:
#4. Write a Python Program to Sort Words in Alphabetic Order?
strin = "Arshad"
strin = strin.lower()
sorted_word = "".join(sorted(list(strin)))
print(sorted_word)

aadhrs


In [28]:
#5. Write a Python Program to Remove Punctuation From a String?
import re
a_string = '!hi. wh?at is the weat[h]er lik?e.'
new_string = re.sub(r'[^\w\s]', '', a_string)
print(new_string)

hi what is the weather like
